name: Run tests with valgrind

on:
  push:
    branches:
      -main
  pull_requet:
    branches:
      -main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make valgrind

    - name: Build project
      run: make

    - name: Run tests with valgrind on all executables
      run: |
        find . -type d -name 'bin' | while read bin_dir; do
          find "$bin_dir" -type f -executable | while read exe; do
            echo "Running valrind on $exe"
            valgrind --leak-check=full --show-leak-kinds=all --track-fds=yes --error-exitcode=1 "$exe"
          done
        done
